CREATE TABLE post (
    id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR2(200 CHAR)  NOT NULL,
    summary     VARCHAR2(500 CHAR),
    content     CLOB                NOT NULL,
    status      VARCHAR2(20 CHAR)   NOT NULL,
    created_at  TIMESTAMP           NOT NULL,
    updated_at  TIMESTAMP           NOT NULL,
    published_at TIMESTAMP
);

CREATE INDEX idx_post_status_published ON post (status, published_at);
