-- 로컬/테스트용 (H2). 운영 스키마는 ../oracle 참고 — 두 파일의 구조를 항상 같이 유지할 것
CREATE TABLE post (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(200)  NOT NULL,
    summary      VARCHAR(500),
    content      CLOB          NOT NULL,
    status       VARCHAR(20)   NOT NULL,
    created_at   TIMESTAMP     NOT NULL,
    updated_at   TIMESTAMP     NOT NULL,
    published_at TIMESTAMP
);

CREATE INDEX idx_post_status_published ON post (status, published_at);
